#    ______ _           _ _____            __ _
#   |  ___| |         (_)  __ \          / _| |
#   | |_  | | _____  ___| /  \/_ __ __ _| |_| |_
#   |  _| | |/ _ \ \/ / | |   | '__/ _` |  _| __|
#   | |   | |  __/>  <| | \__/\ | | (_| | | | |_
#   \_|   |_|\___/_/\_\_|\____/_|  \__,_|_|  \__|

# Made by OlliesWorld

# Config messages
config-reload: '&eFlexi&6Craft &7>> &aConfig file reloaded.'
config-reload-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions to reload the config file!'

# Console messages
no-player-error: '&eFlexi&6Craft &7>> &cOnly players can use this command!'

# Join Leave messages
leave-message: '&eFlexi&6Craft &7>> %player% has &cleft &7the game!'
join-message: '&eFlexi&6Craft &7>> %player% has &ajoined &7the game!'
first-time-join-message: '&e&lFlexi&6&lCraft &7&l>> %player% has &a&ljoined &7&lfor the first time!'

# Kick and Ban messages
ban-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions for the ban command!'
ban-usage: '&eFlexi&6Craft &7>> &cUsage: /ban <player> <Reason>'
ban-no-player: '&eFlexi&6Craft &7>> &cPlayer not found!'
ban-server-message: '&eFlexi&6Craft &7>> %target-player% has been &cbanned &7for: %reason%'
unban-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions for the unban command!'
unban-usage: '&eFlexi&6Craft &7>> &cUsage: /unban <player>'
unban-player-not-banned: '&eFlexi&6Craft &7>>&c %target-player% is not banned!'
unban-player-unbanned: '&eFlexi&6Craft &7>> %target-player% is unbanned!'
kick-usage: '&eFlexi&6Craft &7>> &cUsage: /kick <player> <Reason>'
kick-no-player: '&eFlexi&6Craft &7>> &cPlayer not found!'
kick-message: '&eFlexi&6Craft &7>> %target-player% has been &ckicked &7for: %reason%'

# Mute messages
mute-chat-message: '&eFlexi&6Craft &7>> &cYou are not able to type while being muted!'
mute-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions for the mute command!'

# Fly messages
on-message: '&eFlexi&6Craft &7>> You have &aenabled &7fly!'
off-message: '&eFlexi&6Craft &7>> You have &cdisabled &7fly!'
other-on-message: '&eFlexi&6Craft &7>> &7You have &aenabled &7fly for %other_player%!'
other-off-message: '&eFlexi&6Craft &7>> &7You have &cdisabled &7fly for %other_player%!'
no-other-permission-message: '&eFlexi&6Craft &7>> &cYou have no permissions to make others fly!'
no-permission-message: '&eFlexi&6Craft &7>> &cYou have no permissions to fly!'
player-not-found: '&eFlexi&6Craft &7>> &cPlayer not found!'

# Clear messages
clear-message: '&eFlexi&6Craft &7>> Your inventory has been cleared.'
clear-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions to clear your inventory!'
clear-player-not-found: '&eFlexi&6Craft &7>> &cPlayer %target-player% not found!'

# Repair messages
repair: '&eFlexi&6Craft &7>> &aItem is repaired'
repair-no-perms: '&eFlexi&6Craft &7>> &cYou have no permissions to repair broken stuff!'
repair-no-item: '&eFlexi&6Craft &7>> &cYou must be holding a item to repair it!'
repair-error: '&eFlexi&6Craft &7>> &cThis item can not be repaired'
